name: format codes

on:
  push:
    paths:
      - "**.go"
      - "**.yml"
  workflow_dispatch:

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Formatting Tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install mvdan.cc/gofumpt@latest
          go install github.com/segmentio/golines@latest
          go install github.com/daixiang0/gci@latest

      - name: Format Codes
        run: |
          go mod tidy
          gofmt -w .
          goimports -w .
          gci write . -s standard -s default -s "prefix(github.com/Vivekkumar-IN/EditguardianBot)"
          gofumpt -w -extra .
          golines --max-len=80 .
          go get github.com/Vivekkumar-IN/profanity-check

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "format codes"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - uses: Mattraks/delete-workflow-runs@v2
        with:
          keep_minimum_runs: 0
          retain_days: 0